language: go

go:
  - tip
  - 1.13.x
  - 1.10.x

env:
  - GO111MODULE=on

before_script:
  - rm -f go.sum
  - go get -v github.com/elvinchan/rpcx/...
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - goveralls -service=travis-ci
